src/Entity/Artisan.php
<?php

namespace App\Entity;

use App\Repository\ArtisanRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtisanRepository::class)]
class Artisan extends User
{
    #[ORM\Column]
    private ?bool $etatCompte = null;

    #[ORM\OneToMany(mappedBy: 'idArtisan', targetEntity: Product::class, orphanRemoval: true)]
    private Collection $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }



    public function isEtatCompte(): ?bool
    {
        return $this->etatCompte;
    }

    public function setEtatCompte(bool $etatCompte): static
    {
        $this->etatCompte = $etatCompte;

        return $this;
    }




    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setIdArtisan($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getIdArtisan() === $this) {
                $product->setIdArtisan(null);
            }
        }

        return $this;
    }


}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Reference = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $QteStock = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?Category $category = null;

    #[ORM\ManyToMany(targetEntity: Commande::class, mappedBy: 'produits')]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->Reference;
    }

    public function setReference(string $Reference): static
    {
        $this->Reference = $Reference;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getQteStock(): ?int
    {
        return $this->QteStock;
    }

    public function setQteStock(int $QteStock): static
    {
        $this->QteStock = $QteStock;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->addProduit($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            $commande->removeProduit($this);
        }

        return $this;
    }
}

src/Form/ArtisanType.php
<?php

namespace App\Form;

use App\Entity\Artisan;
use Karser\Recaptcha3Bundle\Form\Recaptcha3Type;
use Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class ArtisanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('adresse')
            ->add('telephone')
            ->add('typeProduit')
            ->add('RGPDConsent', CheckboxType::class, [
                'mapped' => false,
                'constraints' => [
                    new IsTrue([
                        'message' => 'You should agree to our terms.',
                    ]),
                ],
            ])
            ->add('plainPassword', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
            ->add('captcha', Recaptcha3Type::class, [
                'constraints' => new Recaptcha3(),
                'action_name' => 'registerartisan',

            ]);


    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Artisan::class,
        ]);
    }
}

src/Controller/ArtisanController.php
<?php

namespace App\Controller;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;


use App\Entity\Artisan;
use App\Entity\Product;
use App\Entity\ResetPasswordRequest;
use App\Form\Artisan1Type;
use App\Form\ChangePasswordFormType;
use App\Repository\ArtisanRepository;
use App\Repository\ProductRepository;
use App\Repository\ResetPasswordRequestRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;

#[Route('/artisan')]
class ArtisanController extends AbstractController
{

    private \App\Controller\SecurityController $security ;

    public function __construct(SecurityController $security)
    {
        $this->security = $security;
    }

    #[Route('/', name: 'app_artisan_index', methods: ['GET'])]
    public function index(ArtisanRepository $artisanRepository): Response
    {
        return $this->render('artisan/list_artisans.html.twig', [
            'artisans' => $artisanRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_artisan_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $artisan = new Artisan();
        $form = $this->createForm(Artisan1Type::class, $artisan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($artisan);
            $entityManager->flush();

            return $this->redirectToRoute('app_artisan_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('artisan/new.html.twig', [
            'artisan' => $artisan,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_artisan_show', methods: ['GET'])]
    public function show(Artisan $artisan): Response
    {

        return $this->render('artisan/show.html.twig', [
            'artisan' => $artisan,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_artisan_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Artisan $artisan, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Artisan1Type::class, $artisan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_product_artisan_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('artisan/edit.html.twig', [
            'artisan' => $artisan,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_artisan_delete', methods: ['POST'])]
    public function delete(SessionInterface $session,TokenStorageInterface$tokenStorage,Request $request, Artisan $artisan, ResetPasswordRequestRepository $resetPasswordRequest, EntityManagerInterface $entityManager): ?Response
    {

        if ($this->isCsrfTokenValid('delete' . $artisan->getId(), $request->request->get('_token'))) {



            $resetPasswordRequest->deleteResetByIdArtisan($artisan->getId());
            $tokenStorage->setToken(null);
            $session->invalidate();

            $entityManager->remove($artisan);


            $entityManager->flush();


        } else {
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);

        }

        return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);



        //    {{ include('client/_delete_form.html.twig') }}
    }

    /**
     * @throws \Exception
     */
    #[Route('/artisan/products', name: 'app_product_artisan_index', methods: ['GET'])]
    public function showsProductByArtisan(ProductRepository $productRepository, TokenInterface $token): Response
    {

        $artisan = $token->getUser();


        if ($artisan instanceof Artisan) {
            dump($artisan->getRoles());

            return $this->render('artisan/list_artisans.html.twig', [
                'products' => $productRepository->findById($artisan->getId()),
            ]);
        }
        return throw new \Exception('Acces Denied.');
    }

    #[Route('artisan/product/{id}', name: 'app_product_delete', methods: ['POST'])]
    public function DeleteProduct(Request $request, Product $product, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $product->getId(), $request->request->get('_token'))) {
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/editpasswordArtisan', name: 'app_artisan_editpassword', methods: ['GET', 'POST'])]
    public function editPassword(Request $request, UserPasswordHasherInterface $userPasswordHasher, Artisan $artisan, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChangePasswordFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $artisan->setPassword(
                $userPasswordHasher->hashPassword(
                    $artisan,
                    $form->get('plainPassword')->getData()
                )
            );

            $artisan->setRoles(['ROLE_ARTISAN']);

            $entityManager->persist($artisan);
            $entityManager->flush();

            return $this->redirectToRoute('app_product_artisan_index', []);

        }
        return $this->render('artisan/editpassword.html.twig', [
            'form' => $form->createView(),
        ]);


    }


}

templates/artisan/Liste_des_artisans.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artisan {% endblock %}

{% block body %}
    <h1>Client index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Email</th>
            <th>Adresse</th>
            <th>Password</th>
            <th>Telephone</th>
            <th>Roles</th>
            <th>IsVerified</th>
            <th>Genre</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.nom }}</td>
                <td>{{ client.prenom }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.adresse }}</td>
                <td>{{ client.password }}</td>
                <td>{{ client.telephone }}</td>
                <td>{{ client.roles ? client.roles|json_encode : '' }}</td>
                <td>{{ client.isVerified ? 'Yes' : 'No' }}</td>
                <td>{{ client.genre }}</td>
                <td>
                    <a href="{{ path('app_client_show', {'id': client.id}) }}">show</a>
                    <a href="{{ path('app_client_edit', {'id': client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_client_new') }}">Create new</a>
{% endblock %}

templates/artisan/_delete_form.html.twig
<div style="text-align: center;">
    <form method="post" action="{{ path('app_artisan_delete', {'id': artisan.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" style="display: inline-block;">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artisan.id) }}">


        <button class="btn" style="background-color: white  ; color: black;">Delete</button>

    </form>
</div>

templates/artisan/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/artisan/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Artisan{% endblock %}

{% block body %}
    <h1>Edit Artisan</h1>

    {{ include('artisan/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_artisan_show', {'id': app.user.id}) }}">Retour à la liste</a>

    {{ include('artisan/_delete_form.html.twig') }}
{% endblock %}

templates/artisan/editpassword.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div id="layoutSidenav_content">
        {{ form_start(form,{'attr':{'novalidate':'novalidate'}} ) }}
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-xl px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h3 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="user"></i></div>
                                    Modifier mon mot de passe
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-xl px-4 mt-4">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Change password card-->
                        <div class="card mb-4">
                            <div class="card-header">Modifier mot de passe</div>
                            <div class="card-body">
                                <!-- Form Group (current password)-->
                                <div class="mb-3">
                                    {{ form_widget(form.plainPassword) }}
                                    {{ form_errors(form.plainPassword,{'attr':{'class':'text-danger'}}) }}
                                </div>
                                <button type="submit" class="btn btn-primary">Enregistrer</button>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </main>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/artisan/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Artisan index{% endblock %}

{% block body %}
    <h1>Artisan index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Adresse</th>
                <th>Password</th>
                <th>Telephone</th>

                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for artisan in artisans %}
            <tr>
                <td>{{ artisan.id }}</td>
                <td>{{ artisan.nom }}</td>
                <td>{{ artisan.prenom }}</td>
                <td>{{ artisan.email }}</td>
                <td>{{ artisan.adresse }}</td>
                <td>{{ artisan.password }}</td>
                <td>{{ artisan.telephone }}</td>

                <td>
                    <a href="{{ path('app_artisan_show', {'id': artisan.id}) }}">show</a>
                    <a href="{{ path('app_artisan_edit', {'id': artisan.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_artisan_new') }}">Create new</a>
{% endblock %}

templates/artisan/list_artisans.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}




    <section class="shop section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 mb-4">
                    <div class="account-sidebar">
                        <div class="sidebar-list">
                            <a href="dashboard.html" ><i class="far fa-th-large"></i> Dashboard</a>
                            <a href="product.html"><i class="far fa-layer-group active"></i> Products <span>20</span></a>
                            <a href="add-product.html"><i class="far fa-upload"></i> Add New Product</a>
                            <a href="all-order.html"><i class="far fa-shopping-bag"></i> All Orders <span>2</span></a>
                            <a href="vendor-profile.html"><i class="far fa-cog"></i> Account Settings</a>
                            <a href="#"><i class="far fa-lock"></i> Logout</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <a href="{{ path('app_product_new') }}" class="content-action "><i class="fa fa-upload extraClass" aria-hidden="true"></i><span> Create New </span></a>

                    <div class="account-content">
                        <h4 class="account-content-title"><i class="far fa-map-marker-alt"></i> Products</h4>
                        <div class="account-content-table">
                            <div class="table-responsive">
                                <table class="table table-borderless">
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Description</th>
                                        <th>Action</th>
                                    </tr>
                                    {% for product in products %}
                                        <tr class="account-order-list">
                                            <td><div class="product-info">{{ product.id }}</div></td>
                                            <td><div class="product-info">{{ product.nom }}</div></td>
                                            <td><div class="product-info">${{ product.prix }}</div></td>
                                            <td><div class="product-info">{{ product.description }}</div></td>

                                            <td>
                                                <div class="product-info">
                                                    <a href="{{ path('app_product_edit', {'id': product.id}) }}" class="content-action content-action-mr"><i class="far fa-pen"></i></a>
                                                    <a href="{{ path('app_product_show', {'id': product.id}) }}"  class="content-action"><i class="fa fa-info-circle" aria-hidden="true"></i></a>

                                                </div>
                                            </td>
                                        </tr>

                                    {% endfor %}

                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/artisan/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Artisan{% endblock %}

{% block body %}
    <h1>Create new Artisan</h1>

    {{ include('artisan/_form.html.twig') }}

    <a href="{{ path('app_artisan_index') }}">back to list</a>
{% endblock %}

templates/artisan/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artisan{% endblock %}

{% block body %}
    <h1>Artisan</h1>

    <div class="col-xl-12">
        <!-- Account details card-->
        <div class="card mb-4">
            <div class="card-header">Information Profil</div>
            <div class="card-body">
                <div>
                    <!-- Form Row-->
                    <div class="row gx-3 mb-3">
                        <!-- Form Group (first name)-->
                        <div class="col-md-6">
                            <label class="small mb-1" for="inputFirstName">Nom: </label>
                            <span>{{ app.user.nom }}</span>
                        </div>
                        <!-- Form Group (last name)-->
                        <div class="col-md-6">
                            <label class="small mb-1" for="inputLastName">Prénom: </label>
                            <span>{{ app.user.prenom }}</span>
                        </div>
                    </div>
                    <!-- Form Row        -->
                    <div class="row gx-3 mb-3">
                        <!-- Form Group (organization name)-->
                        <div class="col-md-6">
                            <label class="small mb-1" for="inputOrgName">Adresse: </label>
                            <span>{{ app.user.adresse }}</span>
                        </div>
                        <!-- Form Group (location)-->
                        <div class="col-md-6">
                            <label class="small mb-1" for="inputLocation">Ville: </label>
                            <span>{{ app.user.telephone }}</span>
                        </div>
                    </div>
                    <!-- Form Group (email address)-->
                    <div class="mb-3">
                        <label class="small mb-1" for="inputEmailAddress">Adresse e-mail: </label>
                        <span>{{ app.user.email }}</span>
                    </div>
                    <!-- Form Row-->
                    <div class="row gx-3 mb-3">
                        <!-- Form Group (phone number)-->
                        <div class="col-md-6">
                            <label class="small mb-1" for="inputPhone">Numéro de téléphone: </label>
                            <span>{{ app.user.telephone }}</span>
                        </div>
                        <!-- Form Group (birthday)-->
                    </div>
                    </div>
            </div>
        </div>
    </div>

    <style>
        /* Vous pouvez ajuster la taille de la police selon vos besoins */
        .lien-agrandi {
            font-size: 18px; /* Taille de la police en pixels */
        }
    </style>

    <!-- En utilisant une classe CSS pour le lien -->
    <div class="text-center">
        <a class="small lien-agrandi" href="{{ path('app_artisan_edit', {'id': artisan.id}) }}">Modifier</a>
    </div>

    <div class="text-center">
        <a class="small lien-agrandi" href="{{ path('app_artisan_editpassword', {'id': app.user.id}) }}">Modifier mon mot de passe</a>
    </div>



    {{ include('artisan/_delete_form.html.twig') }}

{% endblock %}